version: '2'
services:
    spring-webflux-mongodb:
        image: mongo:3.4.10
        ports:
            - "27017:27017"
        command: mongos --configdb spring-webflux-mongodb-config
    spring-webflux-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    spring-webflux-mongodb-config:
        image: mongo:3.4.10
        container_name: spring-webflux-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
