# This is a basic workflow to help you get started with Actions

name: CI - Build and push Docker images - Kotlin Service

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: contains(toJson(github), 'build kotlin-service')
    name: Build Jar/Docker Image and Publish to DockerHub

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Set up JDK
      - name: JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login to Dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Putback JDK version to 24 because Kotlin limitation support
        run: |
          sed -i 's/<java\.version>25<\/java\.version>/<java\.version>24<\/java\.version>/g' pom.xml

#      - name: Install Custom Spring Data Common Jar
#        run: |
#          mvn install:install-file -Dfile=docs/spring-data-commons-3.2.1-SNAPSHOT.jar -DgroupId=org.springframework.data -DartifactId=spring-data-commons -Dversion=3.2.1-SNAPSHOT -Dpackaging=jar

      # Build Docker image using docker:build

      - name: Create Custom settings.xml
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
                "id": "github",
                "username": "${{ secrets.USERNAME_MAVEN_PKG }}",
                "password": "${{ secrets.PASSWORD_MAVEN_PKG }}"
            },{
                "id": "github-sba",
                "username": "${{ secrets.USERNAME_MAVEN_PKG }}",
                "password": "${{ secrets.PASSWORD_MAVEN_PKG }}"
            }]

      - name: Build Service using docker:build
        run: |
          SPRING_CLOUD_CONSUL_CONFIG_ENABLED=false mvn clean package -DskipTests -q -pl kotlin-service -am -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn docker:build

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./kotlin-service/target/docker/kotlin-service/build
          file: ./kotlin-service/target/docker/kotlin-service/build/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: fielcapao/microservices-design-patterns-kotlin-service:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
